---

- name: Configure New Relic sysmond
  become: yes
  ini_file:
    dest: /etc/newrelic/nrsysmond.cfg
    group: "{{ sansible_newrelic_group }}"
    mode: 0640
    no_extra_spaces: yes
    owner: "{{ sansible_newrelic_user }}"
    section: "{{ item.section | default(None) }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  when: sansible_newrelic_integrations_sysmond_enabled
  with_items: "{{ [
        {
          'option': 'license_key',
          'value': sansible_newrelic_license_key
        },
        {
          'option': 'loglevel',
          'value': sansible_newrelic_log_level
        },
        {
          'option': 'labels',
          'value': sansible_newrelic_labels
        }
      ] + sansible_newrelic_integrations_sysmond_ini_config
    }}"
  notify:
    - restart newrelic sysmond

- name: Start New Relic Sysmond if start on boot enabled
  become: yes
  service:
    name: newrelic-sysmond
    state: started
  when:
    - sansible_newrelic_integrations_sysmond_enabled
    - sansible_newrelic_integrations_sysmond_start_on_boot

- name: Configure New Relic PHP integration
  become: yes
  ini_file:
    dest: "{{ sansible_newrelic_integrations_php_ini_paths_base }}"
    mode: 0644
    section: "{{ item.section | default(None) }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  when:
    - sansible_newrelic_integrations_php_enabled
    - sansible_newrelic_integrations_php_start_on_boot
  with_items: "{{ [
        {
          'option': 'extension',
          'value': '/usr/lib/php/20151012/newrelic.so'
        },
        {
          'option': 'newrelic.license',
          'section': 'newrelic',
          'value': sansible_newrelic_license_key
        },
        {
          'option': 'newrelic.loglevel',
          'section': 'newrelic',
          'value': sansible_newrelic_log_level
        },
        {
          'option': 'newrelic.appname',
          'section': 'newrelic',
          'value': sansible_newrelic_appname_prefix + sansible_newrelic_appname
        },
        {
          'option': 'newrelic.daemon.loglevel',
          'section': 'newrelic',
          'value': sansible_newrelic_log_level
        }
      ] + sansible_newrelic_integrations_php_ini_config
    }}"

- name: Enable New Relic PHP integration
  become: yes
  file:
    dest: "{{ item }}"
    src: "{{ sansible_newrelic_integrations_php_ini_paths_base }}"
    state: link
  with_items: "{{ sansible_newrelic_integrations_php_ini_paths_links }}"
  when:
    - sansible_newrelic_integrations_php_enabled
    - sansible_newrelic_integrations_php_start_on_boot
