---

- name: Install New Relic dependencies
  become: yes
  apt:
    pkg: apt-transport-https
    state: present

- name: Ensure New Relic PGP key is known to the server
  become: yes
  apt_key:
    id: "{{ item }}"
    keyserver: hkp://keyserver.ubuntu.com:80
    state: present
  with_items: "{{ sansible_newrelic_apt_key_ids }}"

- name: Add New Relic APT repository
  become: yes
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items: "{{ sansible_newrelic_apt_repos }}"

- name: Install New Relic Infra
  become: yes
  apt:
    pkg: "newrelic-infra={{ sansible_newrelic_integrations_infra_version }}"
    state: present
  when: sansible_newrelic_integrations_infra_enabled

- name: Disable New Relic Infra service on boot
  become: yes
  service:
    enabled: false
    name: newrelic-infra
  when: sansible_newrelic_integrations_infra_enabled

- name: Install New Relic PHP integration
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
  when: sansible_newrelic_integrations_php_enabled
  with_items:
    - "newrelic-php5-common={{ sansible_newrelic_integrations_php_version }}"
    - "newrelic-daemon={{ sansible_newrelic_integrations_php_version }}"
    - "newrelic-php5={{ sansible_newrelic_integrations_php_version }}"
