---

- name: restart newrelic infra
  become: yes
  service:
    name: newrelic-infra
    state: restarted
  when:
    - sansible_newrelic_integrations_infra_enabled
    - sansible_newrelic_integrations_infra_start_on_boot
