---

- name: Converge
  hosts: all

  pre_tasks:
    - name: Install net-tools
      become: yes
      apt:
        name: net-tools
        update_cache: yes
        cache_valid_time: 3600

  roles:
    - role: sansible.php
      sansible_php_fpm_bin: php-fpm7.0
      sansible_php_path_etc: /etc/php/7.0
      sansible_php_path_fpm_pool: /etc/php/7.0/fpm/pool.d
      sansible_php_version: php7.0

    - role: newrelic
      sansible_newrelic_appname: sansible-newrelic
      sansible_newrelic_integrations_php_enabled: yes
      sansible_newrelic_integrations_php_start_on_boot: yes
      sansible_newrelic_integrations_infra_enabled: yes
      sansible_newrelic_labels:
        org: sansible
        role: newrelic
      sansible_newrelic_license_key: 123456789123456789123456789123456789
